### ISSUE TITLE
Navigation Bar height

### ISSUE THREAD

**Issue by Hirbod** [zobeirhamid/react-native-scrollable-navigation-bar#2]
Hi @zobeirhamid first of all a BIG thank you for this incredible component. Finally a well done and useable collapsible header bar.

Is there any chance to make the height of the navigation bar editable? Currently, it doesn't look perfect on iPhone X, i need to adjust padding and height a bit.

While I can add a paddingTop to "titleStyle", it still doesn't fit perfectly. Looks like the height is fixed in "constants.js".

Any chance to make this editable or any other advice?

![IMG_5228](https://user-images.githubusercontent.com/504909/57363827-2c093980-7182-11e9-8f42-096888843275.jpg)

**Comment by Hirbod** [comment]
![IMG_5229](https://user-images.githubusercontent.com/504909/57363915-5bb84180-7182-11e9-91cb-98ff74bb526c.jpg)


and here another issue related to the fixed height

**Comment by zobeirhamid** [comment]
Tagchen!

Happy to hear that you like the component. I fixed the issue with iPhone X just now, it should look now better. Currently, the NavigationBarComponent is not really customizable, but you still are able to give the ScrollableNavBar your own NavigationBarComponent. You can also set a navigationBarHeight, but I wouldn't recommend in doing so because you cannot customize the paddingTop to it.
But adding the feature to be able to customize the padding shouldn't be so hard and I would really appreciate any contribution. Danke.

**Comment by Hirbod** [comment]
I worked my way around using another approach:

`navigationBarHeight={IS_ANDROID ? 80 : 50}`

And on titleStyle is set a -10 for the top property. Without adjusting the height, the statusbar will look just too big. Auch dir danke für den fix :)
