### ISSUE TITLE
Touch action need surport in header

### ISSUE THREAD

**Issue by FansPro** [zobeirhamid/react-native-scrollable-navigation-bar#22]
#### Used Version:
```
  "react-native-scrollable-navigation-bar": "^2.0.3"
```
#### Question:
- #####  I want use TouchableOpacity to do some action in HeaderForegroundComponent/HeaderBackgroundComponent, But it cann't be valid, has any solution?

**Comment by zobeirhamid** [comment]
Sorry for the ultra late response. I rewrote the whole library, try v3.

**Comment by bjakobson** [comment]
hi, i am still facing this issue

**Comment by MoFerhat** [comment]
Hi @zobeirhamid 

This problem is still current, I wanted to make custom components `<HeaderNavigationBarComponent />` and
`<NavigationBarComponent />` to put touchable icons there but the touch action does not work.

I wanted to abandon the custom components project, to use the `LeftIcons` and `RightIcons` table but the spacing between the icons is not customizable, it is too big for my case and that's a shame.

Also if the title is too long it overlaps the icons...

what good are components if we can't perform any action?

thanks :)
